# -*- coding: utf-8 -*-
{
    "name": 'Mindora Demo 11 — MRP Plus',
    "version": '19.0.1.0.0',
    "category": "Mindora/Demo",
    "summary": 'Advanced manufacturing: PLM, subcontracting, traceability, advanced quality',
    "description": """Advanced manufacturing (L3): PLM, subcontracting, traceability, advanced quality, maintenance and repair.""",
    "author": 'Mindora',
    "website": 'https://github.com/Mindora-Main/clarence-demo',
    "license": 'LGPL-3',
    "depends": [
        'mindora_demo_base',
        'mrp',
        'mrp_workorder',
        'mrp_account',
        'mrp_plm',
        'mrp_subcontracting',
        'mrp_subcontracting_purchase',
        'purchase',
        'purchase_stock',
        'stock',
        'stock_account',
        'stock_barcode',
        'quality_control',
        'quality_mrp',
        'quality_stock',
        'maintenance',
        'mrp_maintenance',
        'repair',
        'account',
        'spreadsheet_dashboard',
    ],
    "data": [

    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
